from collections import OrderedDict
from textwrap import indent

import aspy.yaml


with open(".travis.yml") as f:
    travis = aspy.yaml.ordered_load(f)


matrix = OrderedDict()
for build in travis["matrix"]["include"]:
    tox_env = build.get("env", "nope")
    if not tox_env.startswith("TOXENV="):
        continue
    tox_env = tox_env.split("=", 1)[1]
    python = build["python"]
    # Not supported yet.
    if python.endswith("-dev"):
        continue
    if python == "pypy":
        python = "pypy2"

    matrix[tox_env] = OrderedDict(
        (("python.version", python), ("tox.env", tox_env))
    )

print(indent(aspy.yaml.ordered_dump(matrix), " " * 8))